buildConfiguration:
  buildCommand: npm run build:local
  installDependenciesStep:
    command: npm install
    requiredFiles:
      - package.json
      - package-lock.json
      - .npmrc
dynamicRedirects:
  # This is a rewrite because the status code is 200. It also takes advantage of built-in splat support.
  -
    from: /grey/*
    to: /gray/:splat
    statusCode: 200
  # This is a custom redirect because the status code is 3xx.
staticRedirects:
  -
    from: /grey-redirect
    to: /gray
    statusCode: 308
# adds authentication to your site
authentication:
  policyName: # my-auth-policy the cac policy you created
  includePaths: # the paths which should be included in the auth policy
  excludePaths: # the paths which should be exclude from the auth policy


